### ISSUE TITLE
Barangay and Sub-Municipality

### ISSUE THREAD

**Issue by illanajm** [bkintanar/psgc-api-wrapper#1]
I can't get the list of barangays when I run Barangay::get();
I get a null data;

also in Sub-Municipality there is an error, SubMunicipality class not found

**Comment by bkintanar** [comment]
@illanajm Barangay::get() is not advisable since it will query all the barangays in the Philippines (42,046 barangays), better to query the city, or municipality first.

With regards to your SubMunicipality class not found, can you double check if there's an import usage in your code?

**Comment by illanajm** [comment]
yes I imported the "use PSGC\Facades\SubMunicipality". but it still has an error. Illuminate\Contracts\Container\BindingResolutionException: Target class [SubMunicipality] does not exist.
vendor\laravel\framework\src\Illuminate\Container\Container.php on line 811

**Comment by bkintanar** [comment]
@illanajm OK. Thank you for reporting. I'll check on the error.

**Comment by illanajm** [comment]
Thank you so much

**Comment by illanajm** [comment]
can it integrate also the x and y coordinates for the location in map?

**Comment by bkintanar** [comment]
@illanajm can you do a composer update. I just released 0.4. It should solve your issue with SubMunicipality class not found.

**Comment by bkintanar** [comment]
> can it integrate also the x and y coordinates for the location in map?

I'm afraid not. :)

**Comment by illanajm** [comment]
I run composer update but still the issue is there.

**Comment by bkintanar** [comment]
can you remove vendor directory and run composer update again.

**Comment by illanajm** [comment]
It is now solved. Thanks a lot ^.^. you have to change the name of
municipality and submunicipality in vendor\facades for it was misspelled.
